Решил все задачи из Занятие 1: Основы JavaScript
js-tasks-ru/jsbasic-20220113_bistro1994 pull request #3
Opened 2022-01-19 21:31 UTC by WolffRick

2022-01-19 21:32 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-01-20 12:37 UTC, SinimaWath requested changes

2022-01-20 12:37 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  }
Обычно малое количество правил(меньше 4), можно лаконично уместить в return:
`return str.includes('1xbet') || str.includes('xxx')`

Это как раз тот случай

2022-01-20 12:37 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  else return str;
Такой код достаточно сложно понимать и читать.
https://learn.javascript.ru/coding-style

Его можно переписать вот так в несколько строчек, разделяя код на разные логические блоки:
```
if (str.length > maxlength) {
  return ...
}

return ...
```

2022-01-20 12:37 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  else if (str.lenght == 1) return str[0].toUpperCase();
Это условие не нужно, без него и так будет работать твой код :)

попробуй проверить

2022-01-22 14:34 UTC, WolffRick commented on 1-module/3-task/index.js
> +  else if (str.lenght == 1) return str[0].toUpperCase();
Без условия else if (str.lenght == 1) return str[0].toUpperCase(); код и правда работает 
А вот без if (str == '') return str.charAt(); выдает ошибку проверки на пустую строку

Удалил из этого кода второе условие

2022-01-22 14:42 UTC, WolffRick commented on 1-module/4-task/index.js
> +  }
Действительно, приму к сведению. Постараюсь в будущем такие вещи укорачивать, просто на первых порах так проще самому понять, что к чему. Но не стесняйся бить по рукам, чтобы я сразу привыкал к чистоте кода

2022-01-22 14:45 UTC, WolffRick commented on 1-module/5-task/index.js
> +  else return str;
А вот здесь наоборот попытка слегка укоротить оказалась некорректной. Постараюсь запомнить такие моменты, спасибо за замечание

2022-01-22 14:47 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-01-22 14:47 UTC, WolffRick commented
Поправил все отмеченные места, прокомментировал каждый пункт

2022-01-22 14:53 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-01-24 10:06 UTC, SinimaWath reviewed
Все ок, но чтобы влить ПР, надо решить все задачи, которые ты себе добавил :)

2022-01-28 16:40 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-01-28 16:43 UTC, WolffRick commented
Т.к. случайно ранее добавил задачу из 2 занятия - сдаю оба занятия разом, все проверки пройдены. Задачи из 3 занятия не трогаю до закрытия этого реквеста

2022-01-30 12:29 UTC, SinimaWath approved these changes
Все ок!

2022-01-30 12:30 UTC, merged